CREATE SEQUENCE IF NOT EXISTS application_messages_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS banned_users_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS blocked_users_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS channels_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS channels_invites_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS channels_logs_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS channels_posts_comments_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS channels_posts_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS channels_posts_images_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS channels_posts_likes_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS channels_users_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS chats_messages_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS email_keys_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS group_users_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS groups_actions_messages_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS groups_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS groups_invites_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS groups_messages_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS person_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS users_chats_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS users_friends_id_seq START WITH 1 INCREMENT BY 1;

CREATE TABLE application_messages
(
    user_id     INTEGER                                 NOT NULL,
    message     VARCHAR                                 NOT NULL,
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    sent_date   TIMESTAMP WITHOUT TIME ZONE,
    remove_date TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT application_messages_pkey PRIMARY KEY (id)
);

CREATE TABLE banned_channels_users
(
    channel_id INTEGER NOT NULL,
    user_id    INTEGER NOT NULL,
    CONSTRAINT banned_channels_users_pkey PRIMARY KEY (channel_id, user_id)
);

CREATE TABLE banned_users
(
    id      INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id INTEGER,
    reason  VARCHAR                                  NOT NULL,
    CONSTRAINT banned_users_pkey PRIMARY KEY (id)
);

CREATE TABLE blocked_users
(
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    owner_id     INTEGER,
    blocked_user INTEGER,
    CONSTRAINT blocked_users_pkey PRIMARY KEY (id)
);

CREATE TABLE channels
(
    id                        INTEGER GENERATED BY DEFAULT AS IDENTITY               NOT NULL,
    owner_id                  INTEGER,
    created_at                date                                                   NOT NULL,
    is_private                BOOLEAN                                                NOT NULL,
    name                      VARCHAR                                                NOT NULL,
    is_banned                 BOOLEAN                                                NOT NULL,
    description               VARCHAR,
    image                     VARCHAR DEFAULT '6f03317c-1ab7-4f61-bc4e-932e36258526' NOT NULL,
    is_posts_comments_allowed BOOLEAN                                                NOT NULL,
    is_files_allowed          BOOLEAN DEFAULT TRUE                                   NOT NULL,
    is_invites_allowed        BOOLEAN DEFAULT TRUE                                   NOT NULL,
    web_socket_uuid           VARCHAR                                                NOT NULL,
    CONSTRAINT channels_pkey PRIMARY KEY (id)
);

CREATE TABLE channels_invites
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id      INTEGER,
    channel_id   INTEGER,
    send_time    TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    expired_time TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT channels_invites_pkey PRIMARY KEY (id)
);

CREATE TABLE channels_logs
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    message      VARCHAR                                 NOT NULL,
    channel_id   INTEGER,
    created_at   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    expired_time TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT channels_logs_pkey PRIMARY KEY (id)
);

CREATE TABLE channels_posts
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    channel_id   INTEGER,
    owner_id     INTEGER,
    created_at   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    content_type VARCHAR                                 NOT NULL,
    post         VARCHAR,
    CONSTRAINT channels_posts_pkey PRIMARY KEY (id)
);

CREATE TABLE channels_posts_comments
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    comment      VARCHAR                                 NOT NULL,
    owner_id     INTEGER,
    created_at   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    post_id      INTEGER,
    content_type VARCHAR                                 NOT NULL,
    CONSTRAINT channels_posts_comments_pkey PRIMARY KEY (id)
);

CREATE TABLE channels_posts_files
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    file_uuid    VARCHAR                                 NOT NULL,
    post_id      BIGINT                                  NOT NULL,
    content_type VARCHAR                                 NOT NULL,
    CONSTRAINT channels_posts_images_pkey PRIMARY KEY (id)
);

CREATE TABLE channels_posts_likes
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id INTEGER                                 NOT NULL,
    post_id BIGINT                                  NOT NULL,
    CONSTRAINT channels_posts_likes_pkey PRIMARY KEY (id)
);

CREATE TABLE channels_users
(
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id    INTEGER,
    channel_id INTEGER,
    is_admin   BOOLEAN                                  NOT NULL,
    CONSTRAINT channels_users_pkey PRIMARY KEY (id)
);

CREATE TABLE chats_messages
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    chat          INTEGER,
    message       VARCHAR                                 NOT NULL,
    message_owner INTEGER,
    sent_time     TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    is_read       BOOLEAN                                 NOT NULL,
    content_type  VARCHAR                                 NOT NULL,
    CONSTRAINT chats_messages_pkey PRIMARY KEY (id)
);

CREATE TABLE email_keys
(
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email        VARCHAR                                  NOT NULL,
    key          INTEGER                                  NOT NULL,
    expired_time TIMESTAMP WITHOUT TIME ZONE              NOT NULL,
    attempts     INTEGER                                  NOT NULL,
    CONSTRAINT email_keys_pkey PRIMARY KEY (id)
);

CREATE TABLE flyway_schema_history
(
    installed_rank INTEGER                                   NOT NULL,
    version        VARCHAR(50),
    description    VARCHAR(200)                              NOT NULL,
    type           VARCHAR(20)                               NOT NULL,
    script         VARCHAR(1000)                             NOT NULL,
    checksum       INTEGER,
    installed_by   VARCHAR(100)                              NOT NULL,
    installed_on   TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW() NOT NULL,
    execution_time INTEGER                                   NOT NULL,
    success        BOOLEAN                                   NOT NULL,
    CONSTRAINT flyway_schema_history_pk PRIMARY KEY (installed_rank)
);

CREATE TABLE group_users
(
    id       INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id  INTEGER,
    group_id INTEGER,
    is_admin BOOLEAN                                  NOT NULL,
    CONSTRAINT group_users_pkey PRIMARY KEY (id)
);

CREATE TABLE groups
(
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY               NOT NULL,
    name            VARCHAR                                                NOT NULL,
    owner_id        INTEGER,
    created_at      date                                                   NOT NULL,
    description     VARCHAR,
    image           VARCHAR DEFAULT '393de5ef-bd11-4057-9863-77d49c47c806' NOT NULL,
    web_socket_uuid VARCHAR                                                NOT NULL,
    CONSTRAINT groups_pkey PRIMARY KEY (id)
);

CREATE TABLE groups_actions_messages
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    message   VARCHAR                                 NOT NULL,
    group_id  INTEGER,
    sent_time TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT groups_actions_messages_pkey PRIMARY KEY (id)
);

CREATE TABLE groups_banned_users
(
    user_id  INTEGER NOT NULL,
    group_id INTEGER NOT NULL,
    CONSTRAINT groups_banned_users_pkey PRIMARY KEY (user_id, group_id)
);

CREATE TABLE groups_invites
(
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id      INTEGER                                  NOT NULL,
    group_id     INTEGER                                  NOT NULL,
    sent_time    TIMESTAMP WITHOUT TIME ZONE              NOT NULL,
    expired_time TIMESTAMP WITHOUT TIME ZONE              NOT NULL,
    CONSTRAINT groups_invites_pkey PRIMARY KEY (id)
);

CREATE TABLE groups_messages
(
    message       VARCHAR                                 NOT NULL,
    message_owner INTEGER,
    group_id      INTEGER                                 NOT NULL,
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    sent_time     TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    content_type  VARCHAR                                 NOT NULL,
    CONSTRAINT groups_messages_pkey PRIMARY KEY (id)
);

CREATE TABLE person
(
    id                        INTEGER GENERATED BY DEFAULT AS IDENTITY                                   NOT NULL,
    username                  VARCHAR                                                                    NOT NULL,
    email                     VARCHAR                                                                    NOT NULL,
    password                  VARCHAR                                                                    NOT NULL,
    created_at                TIMESTAMP WITHOUT TIME ZONE,
    role                      VARCHAR                                                                    NOT NULL,
    description               VARCHAR,
    is_private                BOOLEAN                                                                    NOT NULL,
    status                    VARCHAR                     DEFAULT 'REGISTERED'                           NOT NULL,
    image                     VARCHAR                     DEFAULT '3a2cd62f-121a-48b5-b0aa-e54454d4d996' NOT NULL,
    is_banned                 BOOLEAN                     DEFAULT FALSE                                  NOT NULL,
    web_socket_uuid           VARCHAR                     DEFAULT 'uuid'                                 NOT NULL,
    online_status             VARCHAR                     DEFAULT 'OFFLINE'                              NOT NULL,
    last_online_status_update TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW()                                  NOT NULL,
    CONSTRAINT person_pkey PRIMARY KEY (id)
);

CREATE TABLE tokens
(
    id           VARCHAR NOT NULL,
    status       VARCHAR NOT NULL,
    user_id      INTEGER NOT NULL,
    expired_date date,
    CONSTRAINT tokens_pkey PRIMARY KEY (id)
);

CREATE TABLE users_chats
(
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user1           INTEGER,
    user2           INTEGER,
    web_socket_uuid VARCHAR DEFAULT 'uuid'                   NOT NULL,
    CONSTRAINT users_chats_pkey PRIMARY KEY (id)
);

CREATE TABLE users_friends
(
    id        INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    owner_id  INTEGER,
    friend_id INTEGER,
    status    VARCHAR                                  NOT NULL,
    CONSTRAINT users_friends_pkey PRIMARY KEY (id)
);

ALTER TABLE banned_users
    ADD CONSTRAINT banned_users_user_id_key UNIQUE (user_id);

ALTER TABLE channels
    ADD CONSTRAINT channels_name_key UNIQUE (name);

ALTER TABLE channels_posts_files
    ADD CONSTRAINT channels_posts_images_image_uuid_key UNIQUE (file_uuid);

ALTER TABLE email_keys
    ADD CONSTRAINT email_keys_email_key UNIQUE (email);

ALTER TABLE person
    ADD CONSTRAINT person_email_key UNIQUE (email);

ALTER TABLE person
    ADD CONSTRAINT person_username_key UNIQUE (username);

CREATE INDEX flyway_schema_history_s_idx ON flyway_schema_history (success);

ALTER TABLE application_messages
    ADD CONSTRAINT application_messages_user_id_fkey FOREIGN KEY (user_id) REFERENCES person (id) ON DELETE CASCADE;

ALTER TABLE banned_channels_users
    ADD CONSTRAINT banned_channels_users_channel_id_fkey FOREIGN KEY (channel_id) REFERENCES channels (id) ON DELETE CASCADE;

ALTER TABLE banned_channels_users
    ADD CONSTRAINT banned_channels_users_user_id_fkey FOREIGN KEY (user_id) REFERENCES person (id) ON DELETE CASCADE;

ALTER TABLE banned_users
    ADD CONSTRAINT banned_users_user_id_fkey FOREIGN KEY (user_id) REFERENCES person (id) ON DELETE NO ACTION;

ALTER TABLE blocked_users
    ADD CONSTRAINT blocked_users_blocked_user_fkey FOREIGN KEY (blocked_user) REFERENCES person (id) ON DELETE CASCADE;

ALTER TABLE blocked_users
    ADD CONSTRAINT blocked_users_owner_id_fkey FOREIGN KEY (owner_id) REFERENCES person (id) ON DELETE CASCADE;

ALTER TABLE channels_invites
    ADD CONSTRAINT channels_invites_channel_id_fkey FOREIGN KEY (channel_id) REFERENCES channels (id) ON DELETE CASCADE;

ALTER TABLE channels_invites
    ADD CONSTRAINT channels_invites_user_id_fkey FOREIGN KEY (user_id) REFERENCES person (id) ON DELETE CASCADE;

ALTER TABLE channels_logs
    ADD CONSTRAINT channels_logs_channel_id_fkey FOREIGN KEY (channel_id) REFERENCES channels (id) ON DELETE CASCADE;

ALTER TABLE channels
    ADD CONSTRAINT channels_owner_id_fkey FOREIGN KEY (owner_id) REFERENCES person (id) ON DELETE CASCADE;

ALTER TABLE channels_posts
    ADD CONSTRAINT channels_posts_channel_id_fkey FOREIGN KEY (channel_id) REFERENCES channels (id) ON DELETE CASCADE;

ALTER TABLE channels_posts_comments
    ADD CONSTRAINT channels_posts_comments_owner_id_fkey FOREIGN KEY (owner_id) REFERENCES channels_users (id) ON DELETE CASCADE;

ALTER TABLE channels_posts_comments
    ADD CONSTRAINT channels_posts_comments_post_id_fkey FOREIGN KEY (post_id) REFERENCES channels_posts (id) ON DELETE CASCADE;

ALTER TABLE channels_posts_files
    ADD CONSTRAINT channels_posts_images_post_id_fkey FOREIGN KEY (post_id) REFERENCES channels_posts (id) ON DELETE CASCADE;

ALTER TABLE channels_posts_likes
    ADD CONSTRAINT channels_posts_likes_post_id_fkey FOREIGN KEY (post_id) REFERENCES channels_posts (id) ON DELETE CASCADE;

ALTER TABLE channels_posts_likes
    ADD CONSTRAINT channels_posts_likes_user_id_fkey FOREIGN KEY (user_id) REFERENCES person (id) ON DELETE CASCADE;

ALTER TABLE channels_posts
    ADD CONSTRAINT channels_posts_owner_id_fkey FOREIGN KEY (owner_id) REFERENCES channels_users (id) ON DELETE CASCADE;

ALTER TABLE channels_users
    ADD CONSTRAINT channels_users_channel_id_fkey FOREIGN KEY (channel_id) REFERENCES channels (id) ON DELETE CASCADE;

ALTER TABLE channels_users
    ADD CONSTRAINT channels_users_user_id_fkey FOREIGN KEY (user_id) REFERENCES person (id) ON DELETE CASCADE;

ALTER TABLE chats_messages
    ADD CONSTRAINT chats_messages_chat_fkey FOREIGN KEY (chat) REFERENCES users_chats (id) ON DELETE CASCADE;

ALTER TABLE chats_messages
    ADD CONSTRAINT chats_messages_message_owner_fkey FOREIGN KEY (message_owner) REFERENCES person (id) ON DELETE CASCADE;

ALTER TABLE group_users
    ADD CONSTRAINT group_users_group_id_fkey FOREIGN KEY (group_id) REFERENCES groups (id) ON DELETE CASCADE;

ALTER TABLE group_users
    ADD CONSTRAINT group_users_user_id_fkey FOREIGN KEY (user_id) REFERENCES person (id) ON DELETE CASCADE;

ALTER TABLE groups_actions_messages
    ADD CONSTRAINT groups_actions_messages_group_id_fkey FOREIGN KEY (group_id) REFERENCES groups (id) ON DELETE CASCADE;

ALTER TABLE groups_banned_users
    ADD CONSTRAINT groups_banned_users_group_id_fkey FOREIGN KEY (group_id) REFERENCES groups (id) ON DELETE CASCADE;

ALTER TABLE groups_banned_users
    ADD CONSTRAINT groups_banned_users_user_id_fkey FOREIGN KEY (user_id) REFERENCES person (id) ON DELETE CASCADE;

ALTER TABLE groups_invites
    ADD CONSTRAINT groups_invites_group_id_fkey FOREIGN KEY (group_id) REFERENCES groups (id) ON DELETE CASCADE;

ALTER TABLE groups_invites
    ADD CONSTRAINT groups_invites_user_id_fkey FOREIGN KEY (user_id) REFERENCES person (id) ON DELETE CASCADE;

ALTER TABLE groups_messages
    ADD CONSTRAINT groups_messages_group_id_fkey FOREIGN KEY (group_id) REFERENCES groups (id) ON DELETE CASCADE;

ALTER TABLE groups_messages
    ADD CONSTRAINT groups_messages_message_owner_fkey FOREIGN KEY (message_owner) REFERENCES person (id) ON DELETE CASCADE;

ALTER TABLE groups
    ADD CONSTRAINT groups_owner_id_fkey FOREIGN KEY (owner_id) REFERENCES person (id) ON DELETE CASCADE;

ALTER TABLE tokens
    ADD CONSTRAINT tokens_user_id_fkey FOREIGN KEY (user_id) REFERENCES person (id) ON DELETE CASCADE;

ALTER TABLE users_chats
    ADD CONSTRAINT users_chats_user1_fkey FOREIGN KEY (user1) REFERENCES person (id) ON DELETE CASCADE;

ALTER TABLE users_chats
    ADD CONSTRAINT users_chats_user2_fkey FOREIGN KEY (user2) REFERENCES person (id) ON DELETE CASCADE;

ALTER TABLE users_friends
    ADD CONSTRAINT users_friends_user1_id_fkey FOREIGN KEY (owner_id) REFERENCES person (id) ON DELETE CASCADE;

ALTER TABLE users_friends
    ADD CONSTRAINT users_friends_user2_id_fkey FOREIGN KEY (friend_id) REFERENCES person (id) ON DELETE CASCADE;